#.properties 계층구조 중복 발생
#yml, yaml을 통해 들여쓰기 계층구조 사용
#port 번호 변경 (default 8080)
#server:
#port: 8081

spring:
  mvc:
    pathmatch:
#      springboot 2.4 이상에서는 기본적으로 PathPatternParser 를 사용하고 있는데,
#      springfox와 같은 일부 라이브러리에서는 해당 PathPattern rule 과 충돌나는 경우가 있어 path 방식을 변경/
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 0430aa
  jpa:
    database: mysql
#    innoDB사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
#    테이블은 생성해주나, 스키마는 반드시 사전에 생성필요.
    generate-ddl: true
#    jpa는 인터페이스이고, hibernate구현체(실질적 기능 구현)
    hibernate:
#      create옵션은 매번 table을 drop후 재생성
#      update옵션은 변경사항만 alter를 적용하고 기존의 데이터 유지
#      변경사항중에 주로 추가사항만을 반영하고, 삭제나 수정사항은 반영안되는경우도 있음.
#      validate는 실제DB와의 차이만을 check
      ddl-auto: create
#      콘솔창에 ddl, dml문을 출력하여 보여주는 옵션
    show_sql: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml