# .properties ? ????? ?? ??.
# yml(yaml) ? ?? ???? ???? ??.

# port ?? ?? ?
# default = 8080
#server :
#  port : 8081

spring :
  datasource :
    driver-class-name : org.mariadb.jdbc.Driver
    url : jdbc:mariadb://jsangmin.co.kr:11000/basic
    username : root
    password : 1234